#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Apr 05, 2025 12:30:29 PM JST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #ffffff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 331x589+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_1_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "1" 
    vTcl:DefineAlias "$top.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_2_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "2" 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_3_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "3" 
    vTcl:DefineAlias "$top.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_4_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "4" 
    vTcl:DefineAlias "$top.but51" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_5_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "5" 
    vTcl:DefineAlias "$top.but52" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_6_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "6" 
    vTcl:DefineAlias "$top.but53" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_7_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "7" 
    vTcl:DefineAlias "$top.but54" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but55" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_8_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "8" 
    vTcl:DefineAlias "$top.but55" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_9_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "9" 
    vTcl:DefineAlias "$top.but57" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_star_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "*" 
    vTcl:DefineAlias "$top.but58" "Button10" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but59" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_0_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "0" 
    vTcl:DefineAlias "$top.but59" "Button11" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but60" \
        -activebackground #d9d9d9 -activeforeground black -background #ffffff \
        -command "btn_sharp_clk" -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF ExtraBold} -size 36 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "#" 
    vTcl:DefineAlias "$top.but60" "Button12" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound center -disabledforeground #a3a3a3 \
        -font "-family {나눔고딕OTF} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "알림 메시지입니다" -textvariable "msg_var" 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    set msg_var {알림 메시지입니다}
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {나눔고딕OTF} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "입력
초기화" 
    vTcl:DefineAlias "$top.but47" "Button13" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can47" \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 190 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 331 
    vTcl:DefineAlias "$top.can47" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but48 \
        -in $top -x 10 -y 240 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 120 -y 240 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 230 -y 240 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 10 -y 330 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 120 -y 330 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 230 -y 330 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 10 -y 420 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 120 -y 420 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 230 -y 420 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 10 -y 510 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 120 -y 510 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 230 -y 510 -width 87 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -y 190 -width 267 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 270 -y 190 -width 57 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can47 \
        -in $top -x 0 -y 0 -width 331 -relwidth 0 -height 190 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

