#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 05, 2025 10:07:19 AM JST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import face_doorlock_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("331x589+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("스마트 도어락")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.msg_var = tk.StringVar()

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.03, rely=0.407, height=66, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(command=face_doorlock_support.btn_1_clk)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''1''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.363, rely=0.407, height=66, width=87)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(command=face_doorlock_support.btn_2_clk)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''2''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.695, rely=0.407, height=66, width=87)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(command=face_doorlock_support.btn_3_clk)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''3''')

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.03, rely=0.56, height=66, width=87)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#ffffff")
        self.Button4.configure(command=face_doorlock_support.btn_4_clk)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="#000000")
        self.Button4.configure(text='''4''')

        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.363, rely=0.56, height=66, width=87)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#ffffff")
        self.Button5.configure(command=face_doorlock_support.btn_5_clk)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="#000000")
        self.Button5.configure(text='''5''')

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.695, rely=0.56, height=66, width=87)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#ffffff")
        self.Button6.configure(command=face_doorlock_support.btn_6_clk)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="#000000")
        self.Button6.configure(text='''6''')

        self.Button7 = tk.Button(self.top)
        self.Button7.place(relx=0.03, rely=0.713, height=66, width=87)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="black")
        self.Button7.configure(background="#ffffff")
        self.Button7.configure(command=face_doorlock_support.btn_7_clk)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="#000000")
        self.Button7.configure(text='''7''')

        self.Button8 = tk.Button(self.top)
        self.Button8.place(relx=0.363, rely=0.713, height=66, width=87)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="black")
        self.Button8.configure(background="#ffffff")
        self.Button8.configure(command=face_doorlock_support.btn_8_clk)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="#000000")
        self.Button8.configure(text='''8''')

        self.Button9 = tk.Button(self.top)
        self.Button9.place(relx=0.695, rely=0.713, height=66, width=87)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="black")
        self.Button9.configure(background="#ffffff")
        self.Button9.configure(command=face_doorlock_support.btn_9_clk)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="#000000")
        self.Button9.configure(text='''9''')

        self.Button10 = tk.Button(self.top)
        self.Button10.place(relx=0.03, rely=0.866, height=66, width=87)
        self.Button10.configure(activebackground="#d9d9d9")
        self.Button10.configure(activeforeground="black")
        self.Button10.configure(background="#ffffff")
        self.Button10.configure(command=face_doorlock_support.btn_star_clk)
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="#000000")
        self.Button10.configure(text='''*''')

        self.Button11 = tk.Button(self.top)
        self.Button11.place(relx=0.363, rely=0.866, height=66, width=87)
        self.Button11.configure(activebackground="#d9d9d9")
        self.Button11.configure(activeforeground="black")
        self.Button11.configure(background="#ffffff")
        self.Button11.configure(command=face_doorlock_support.btn_0_clk)
        self.Button11.configure(disabledforeground="#a3a3a3")
        self.Button11.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button11.configure(foreground="#000000")
        self.Button11.configure(highlightbackground="#d9d9d9")
        self.Button11.configure(highlightcolor="#000000")
        self.Button11.configure(text='''0''')

        self.Button12 = tk.Button(self.top)
        self.Button12.place(relx=0.695, rely=0.866, height=66, width=87)
        self.Button12.configure(activebackground="#d9d9d9")
        self.Button12.configure(activeforeground="black")
        self.Button12.configure(background="#ffffff")
        self.Button12.configure(command=face_doorlock_support.btn_sharp_clk)
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(font="-family {나눔고딕OTF ExtraBold} -size 36 -weight bold")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="#000000")
        self.Button12.configure(text='''#''')

        self.Button13 = tk.Button(self.top)
        self.Button13.place(relx=0.816, rely=0.323, height=36, width=57)
        self.Button13.configure(activebackground="#d9d9d9")
        self.Button13.configure(activeforeground="black")
        self.Button13.configure(background="#d9d9d9")
        self.Button13.configure(command=face_doorlock_support.btn_reset)
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(font="-family {나눔고딕OTF} -size 9")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="#000000")
        self.Button13.configure(text='''입력\n초기화''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.323, height=41, width=267)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='center')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {나눔고딕OTF} -size 10")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''알림 메시지입니다''')
        self.Label1.configure(textvariable=self.msg_var)
        self.msg_var.set('''알림 메시지입니다''')

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=0.323, relwidth=1.0)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="#000000")
        self.Canvas1.configure(insertbackground="#000000")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")
        self.Canvas1.configure(selectforeground="black")


def start_up():
    face_doorlock_support.main()

if __name__ == '__main__':
    face_doorlock_support.main()




